// sprite list
window.sprites_meta = [
    ['sprites/terrain/dirt-01.png', {}],
    ['sprites/terrain/dirt-02.png', {}],
    ['sprites/terrain/dirt-03.png', {}],
    ['sprites/terrain/dirt-04.png', {}],
    ['sprites/terrain/dirt-05.png', {}],
    ['sprites/terrain/dirt-06.png', {}],
    ['sprites/terrain/dirt-rocks-01.png', {}],
    ['sprites/terrain/dirt-B-01.png', {}],
    ['sprites/terrain/dirt-B-02.png', {}],
    ['sprites/terrain/dirt-L-01.png', {}],
    ['sprites/terrain/dirt-LB-01.png', {}],
    ['sprites/terrain/dirt-RB-01.png', {}],
    ['sprites/terrain/dirt-grass-01.png', {}],
    ['sprites/terrain/dirt-grass-02.png', {}],
    ['sprites/terrain/dirt-grass-03.png', {}],
    ['sprites/terrain/dirt-grass-side-RB-01.png', {}],
    ['sprites/terrain/dirt-grass-side-LB-01.png', {}],
    ['sprites/terrain/dirt-grass-side-R-01.png', {}],
    ['sprites/terrain/dirt-grass-side-L-01.png', {}],
    ['sprites/terrain/dirt-corner-L-01.png', {}],
    ['sprites/terrain/dirt-corner-R-01.png', {}],
    ['sprites/terrain/dirt-grass-corner-L-01.png', {}],
    ['sprites/terrain/dirt-grass-corner-R-01.png', {}],
    ['sprites/terrain/dirt-grass-corner-LB-01.png', {}],
    ['sprites/terrain/dirt-grass-corner-RB-01.png', {}],
    ['sprites/terrain/dirt-grass-corner-TL-01.png', {}],
    ['sprites/terrain/dirt-grass-corner-TR-01.png', {}],
    ['sprites/terrain/dirt-grass-hanging-L-01.png', {}],
    ['sprites/terrain/dirt-grass-hanging-R-01.png', {}],
    ['sprites/terrain/dirt-grass-hanging-01.png', {}],
    ['sprites/terrain/dirt-grass-hanging-02.png', {}],
    ['sprites/objects/fire-01.png', {deadly:true, dynamic:true, w:32, h:32, cycle:[[0, 0, 5],[32, 0, 5],[64, 0, 5]]}],
    ['sprites/terrain/spikes-dirt-01.png', {deadly:true}],
    ['sprites/terrain/spikes-grass-L-01.png', {deadly:true}],
    ['sprites/terrain/spikes-grass-R-01.png', {deadly:true}],
    ['sprites/objects/sign.png', {inert:true}],
    ['sprites/objects/sign-01.png', {inert:true}],
    ['sprites/objects/sign-arrow.png', {inert:true}],
    ['sprites/terrain/grass-01.png', {inert:true, destructible:true}],
    ['sprites/terrain/grass-02.png', {inert:true, destructible:true}],
    ['sprites/terrain/grass-03.png', {inert:true, destructible:true}],
    ['sprites/terrain/bush-01.png', {inert:true, destructible:true}],
    ['sprites/terrain/bush-02.png', {inert:true, destructible:true}],
    ['sprites/terrain/stump-01.png', {inert:true, destructible:true}],
    ['sprites/terrain/rock-01.png', {dynamic:true, mass:10, destructible:true}],
    ['sprites/terrain/rock-02.png', {dynamic:true, mass:10,destructible:true}],
    ['sprites/terrain/rock-column-01.png', {dynamic:true, mass:10}],
    ['sprites/terrain/rock-column-02.png', {dynamic:true, mass:10}],
    ['sprites/terrain/water-top-01.png', {front:true, opacity:0.7, w:32, h:32, cycle:[[0, 0, 9],[32, 0, 11],[64, 0, 9]]}],
    ['sprites/terrain/bamboo-01.png', {inert:true, destructible:true}],
    ['sprites/objects/crate-01.png', {dynamic:true, destructible:true, mass:1}],
    ['sprites/objects/crate-02.png', {dynamic:true, destructible:true, mass:1}],
    ['sprites/chars/miner.png', {player:true}],
    ['sprites/chars/duck.png', {dynamic:true, destructible:true, w:32, h:32, cycle:[[0, 0, 8], [35, 0, 8]], duck:true}],
]