// sprite list
window.sprites_meta = [
    ['sprites/terrain/dirt-01.png', {}],
    ['sprites/terrain/dirt-02.png', {}],
    ['sprites/terrain/dirt-03.png', {}],
    ['sprites/terrain/dirt-04.png', {}],
    ['sprites/terrain/dirt-05.png', {}],
    ['sprites/terrain/dirt-06.png', {}],
    ['sprites/terrain/dirt-B-01.png', {}],
    ['sprites/terrain/dirt-B-02.png', {}],
    ['sprites/terrain/dirt-L-01.png', {}],
    ['sprites/terrain/dirt-LB-01.png', {}],
    ['sprites/terrain/dirt-RB-01.png', {}],
    ['sprites/terrain/dirt-grass-01.png', {}],
    ['sprites/terrain/dirt-grass-02.png', {}],
    ['sprites/terrain/dirt-grass-03.png', {}],
    ['sprites/terrain/dirt-grass-side-RB-01.png', {}],
    ['sprites/terrain/dirt-corner-L-01.png', {}],
    ['sprites/terrain/dirt-corner-R-01.png', {}],
    ['sprites/terrain/dirt-grass-corner-L-01.png', {}],
    ['sprites/terrain/dirt-grass-corner-R-01.png', {}],
    ['sprites/terrain/dirt-grass-corner-LB-01.png', {}],
    ['sprites/terrain/dirt-grass-corner-RB-01.png', {}],
    ['sprites/terrain/dirt-grass-hanging-L-01.png', {}],
    ['sprites/terrain/dirt-grass-hanging-R-01.png', {}],
    ['sprites/terrain/dirt-grass-hanging-01.png', {}],
    ['sprites/terrain/dirt-grass-hanging-02.png', {}],
    ['sprites/terrain/grass-01.png', {inhert:true, destructible:true}],
    ['sprites/terrain/grass-02.png', {inhert:true, destructible:true}],
    ['sprites/terrain/grass-03.png', {inhert:true, destructible:true}],
    ['sprites/terrain/bush-01.png', {inhert:true, destructible:true}],
    ['sprites/terrain/bush-02.png', {inhert:true, destructible:true}],
    ['sprites/terrain/stump-01.png', {inhert:true, destructible:true}],
    ['sprites/terrain/bamboo-01.png', {inhert:true, destructible:true}],
    ['sprites/objects/crate-01.png', {dynamic:true, destructible:true}],
]
