

var cards = [
    {
        "title": "Water Grant",
        "discard": ['water'],
        "cost": ['dollar', 'dollar'],
        "img": "cards/water.png",
        "production": ['water'],
        "copies": 5,
    },
    {
        "title": "Cement Factory",
        "discard": ['cement'],
        "cost": ['dollar', 'dollar'],
        "img": "cards/cement.png",
        "production": ['cement'],
        "copies": 5,
    },
    {
        "title": "Hydro",
        "discard": ['water'],
        "cost": ['water', 'water', 'cement', 'cement', 'dollar'],
        "img": "cards/hydro.png",
        "production": ['energy', 'energy', 'vp-3'],
        "copies": 3,
    },
    {
        "title": "Nuclear",
        "discard": ['nuclear'],
        "cost": ['water', 'cement', 'dollar', 'dollar', 'dollar'],
        "img": "cards/nuclear-2.png",
        "production": ['energy', 'nuclear', 'vp-3'],
        "copies": 3,
    },
    {
        "title": "Wind Onshore",
        "discard": ['energy'],
        "cost": ['cement', 'dollar'],
        "img": "cards/wind.png",
        "production": ['energy'],
        "copies": 4,
    },
    {
        "title": "Battery Array",
        "discard": ['energy'],
        "cost": ['dollar', 'dollar'],
        "img": "cards/battery.jpg",
        "production": ['energy-storage'],
        "copies": 3,
    },
    {
        "title": "Subsidy",
        "discard": ['energy'],
        "cost": ['dollar', 'dollar'],
        "img": "cards/subsidy.png",
        "production": ['dollar'],
        "copies": 4,
    },
    {
        "title": "Research Lab",
        "discard": ['research'],
        "cost": ['nuclear', 'dollar', 'energy'],
        "img": "cards/research.png",
        "production": ['research', '1-card'],
        "copies": 3,
    },
    {
        "title": "Solar Power",
        "discard": ['research'],
        "cost": ['energy', 'dollar'],
        "img": "cards/solar.png",
        "production": ['energy'],
        "copies": 3,
    },
    {
        "title": "Fast Trains",
        "discard": ['research'],
        "cost": ['energy', 'energy', 'energy', 'energy', 'energy', 'dollar'],
        "img": "cards/train.png",
        "production": ['vp-6'],
        "copies": 2,
    },
    {
        "title": "Atomic<br>Shipping<br>Container",
        "discard": ['nuclear'],
        "cost": ['research', 'research', 'nuclear', 'nuclear'],
        "img": "cards/atomic-shipping.png",
        "production": ['dollar', 'vp-4'],
        "copies": 2,
    },
    {
        "title": "Water Park",
        "discard": ['water'],
        "cost": ['dollar', 'water', 'cement', 'energy'],
        "img": "cards/water-park.png",
        "production": ['dollar', 'vp-2'],
        "copies": 2,
    },
]